### PR TITLE
廖書賢Pull request

### PR DESCRIPTION
**Pull request by Logan645**
廖書賢 first pull request

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should setup protection rule for `main` branch.

**Comment by Logan645** [comment]
I just setup protection rule for `main` branch .

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page or I cannot do anything for you.

**Review by cwpeng — APPROVED** [review]
OK. Remember to merge pull request after review approval.

**Pull request merged**
