### PR TITLE
廖書賢

### PR DESCRIPTION
**Pull request by Logan645**
http://52.197.169.187:3000
http://52.197.169.187:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Many layout details and other issues you should put more attentions on.
52 197 169 187_3000_attraction_2

**Comment by Logan645** [comment]
Sorry.
I revised layout.
http://52.197.169.187:3000/
http://52.197.169.187:3000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Border of reservation button.
2. Size and color of radio button.

**Comment by Logan645** [comment]
I revised .
1. Border of reservation button.
2. Size and color of radio button.

http://52.197.169.187:3000/
http://52.197.169.187:3000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
