### PR TITLE
廖書賢

### PR DESCRIPTION
**Pull request by Logan645**
http://52.197.169.187:3000/api/attractions?page=1
http://52.197.169.187:3000/api/attractions?page=0&keyword=藝文館所
http://52.197.169.187:3000/api/attractions?page=0&keyword=北
http://52.197.169.187:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but your every field name gets two additional quotes in the front and end of words.

Solve this issue and re-request review.

**Comment by Logan645** [comment]
I remove the additional quotes.

**Comment by Logan645** [comment]
http://52.197.169.187:3000/api/attractions?page=1
http://52.197.169.187:3000/api/attractions?page=0&keyword=藝文館所http://52.197.169.187:3000/api/attractions?page=0&keyword=北
http://52.197.169.187:3000/api/attraction/10
I remove the additional quotes.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
