### PR TITLE
廖書賢 Logan Liao

### PR DESCRIPTION
**Pull request by Logan645**
Week2 mission complete

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Paste your live URL for testing.

**Comment by Logan645** [comment]
Sorry, I forget that.
Here it is.
http://52.197.169.187:3000/
thanks.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Left padding of keyword input should not be 0.
2. Some content will be cover on the top of header bar, shown as below:

**Comment by Logan645** [comment]
http://52.197.169.187:3000/
I fix those problems.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
